      - name: Save uncompressed (برای مخازن با Git LFS)
        run: |
          docker save ghcr.io/m-logique/fluffychat-building-bundle:44233fc3b0ffa2ab0a5bde6178a7c77597143c49 -o fluffychat-image.tar
          # توجه: این فایل ممکن است چند گیگابایت باشد!
      
      - name: Push to repository (نیاز به Git LFS)
        run: |
          git lfs track "*.tar"
          git add .gitattributes fluffychat-image.tar
          git commit -m "Add Docker image bundle"
          git push
